stages:
  - test
  - pypi

test:
  stage: test
  image: python:3.9
  script:
    - apt-get update
      && DEBIAN_FRONTEND=noninteractive
      apt-get install --no-install-recommends -y
      git
    - pip install poetry
    - poetry install
    - poetry run pytest --cov=metro tests/* --cov-report=xml
    - poetry run coverage report
  only:
    - merge_requests
    - master


push-to-pypi:
  stage: pypi
  image: python:3.9
  script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y git
    - pip install poetry
    - poetry install
    - ***REMOVED***
    - ***REMOVED***
  only:
    - master
